@id=607a44ee-774f-4f2b-ae97-d6f4a98896ca

PUT http://localhost:5223/contractors/{{id}}
Content-Type: application/json

{
    "name": "Juan Paul II",
    "email": "JP2@vatican.it",
    "password": "TakJakPanJezusPowiedział"
}