@id=f19110f3-8663-41a7-bb98-3bd057b33f08

PUT http://localhost:5223/contractors/{{id}}
Content-Type: application/json

{
    "name": "Juan Paul II",
    "email": "JP2@vatican.it",
    "password": "TakJakPanJezusPowiedział"
}