POST http://localhost:5223/freeterms
Content-Type: application/json

{
    "contractorId": "e17cc2ff-cc32-4b56-b367-9c20b2d3f679",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T08:00:00"
}